



import img_0   from "../images/bestSalling/image.png"
import img_1 from "../images/bestSalling/image (1).png"
import img_2 from "../images/bestSalling/image (2).png"
import img_3 from "../images/bestSalling/image (3).png"


const newPageItem =[
    {
        id:1,
        img: img_0,
        price: 199,
        name: "حزاء رياضي رجالي",
        rating: 4,
        sall: false,
        new: true,
        like: true ,
    },
    {
        id:2,
        img: img_3,
        price: 199,
        name: "حزاء رياضي رجالي",
        rating: 4,
        sall: true,
        new: true,
        like: true,
    },
    {
        id:3,
        img: img_2,
        price: 199,
        name: "حزاء رياضي رجالي",
        rating: 4,
        sall: false,
        new: true,
        like: false ,
    },
    {
        id:4,
        img: img_1,
        price: 199,
        name: "حزاء رياضي رجالي",
        rating: 4,
        sall: false,
        new: true,
        like: false ,
    },
    {
        id:5,
        img: img_0,
        price: 199,
        name: "حزاء رياضي رجالي",
        rating: 4,
        sall: false,
        new: true,
        like: true ,
    },
    {
        id:6,
        img: img_0,
        price: 199,
        name: "حزاء رياضي رجالي",
        rating: 4,
        sall: false,
        new: true,
        like: true ,
    },
    {
        id:7,
        img: img_3,
        price: 199,
        name: "حزاء رياضي رجالي",
        rating: 4,
        sall: true,
        new: true,
        like: true,
    },
    {
        id:8,
        img: img_2,
        price: 199,
        name: "حزاء رياضي رجالي",
        rating: 4,
        sall: false,
        new: true,
        like: false ,
    },
    {
        id:9,
        img: img_1,
        price: 199,
        name: "حزاء رياضي رجالي",
        rating: 4,
        sall: false,
        new: true,
        like: false ,
    },
    {
        id:10,
        img: img_0,
        price: 199,
        name: "حزاء رياضي رجالي",
        rating: 4,
        sall: false,
        new: true,
        like: true ,
    },{
        id:11,
        img: img_0,
        price: 199,
        name: "حزاء رياضي رجالي",
        rating: 4,
        sall: false,
        new: true,
        like: true ,
    },
    {
        id:12,
        img: img_3,
        price: 199,
        name: "حزاء رياضي رجالي",
        rating: 4,
        sall: true,
        new: true,
        like: true,
    },
    {
        id:13,
        img: img_2,
        price: 199,
        name: "حزاء رياضي رجالي",
        rating: 4,
        sall: false,
        new: true,
        like: false ,
    },
    {
        id:14,
        img: img_1,
        price: 199,
        name: "حزاء رياضي رجالي",
        rating: 4,
        sall: false,
        new: true,
        like: false ,
    },
    {
        id:15,
        img: img_0,
        price: 199,
        name: "حزاء رياضي رجالي",
        rating: 4,
        sall: false,
        new: true,
        like: true ,
    }
    ,{
        id:16,
        img: img_0,
        price: 199,
        name: "حزاء رياضي رجالي",
        rating: 4,
        sall: false,
        new: true,
        like: true ,
    },
    {
        id:17,
        img: img_3,
        price: 199,
        name: "حزاء رياضي رجالي",
        rating: 4,
        sall: true,
        new: true,
        like: true,
    },
    {
        id:18,
        img: img_2,
        price: 199,
        name: "حزاء رياضي رجالي",
        rating: 4,
        sall: false,
        new: true,
        like: false ,
    },
    {
        id:19,
        img: img_1,
        price: 199,
        name: "حزاء رياضي رجالي",
        rating: 4,
        sall: false,
        new: true,
        like: false ,
    },
    {
        id:20,
        img: img_0,
        price: 199,
        name: "حزاء رياضي رجالي",
        rating: 4,
        sall: false,
        new: true,
        like: true ,
    },{
        id:21,
        img: img_0,
        price: 199,
        name: "حزاء رياضي رجالي",
        rating: 4,
        sall: false,
        new: true,
        like: true ,
    },
    {
        id:22,
        img: img_3,
        price: 199,
        name: "حزاء رياضي رجالي",
        rating: 4,
        sall: true,
        new: true,
        like: true,
    },
    {
        id:23,
        img: img_2,
        price: 199,
        name: "حزاء رياضي رجالي",
        rating: 4,
        sall: false,
        new: true,
        like: false ,
    },
    {
        id:24,
        img: img_1,
        price: 199,
        name: "حزاء رياضي رجالي",
        rating: 4,
        sall: false,
        new: true,
        like: false ,
    },
    {
        id:25,
        img: img_0,
        price: 199,
        name: "حزاء رياضي رجالي",
        rating: 4,
        sall: false,
        new: true,
        like: true ,
    }
]



export default newPageItem ;
